### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by wangharris** [TolgaTatli/Moon#211]
I added a new font as follows
```css
@font-face{
  font-family: 'FZZH';
  src: url("../fonts/FZZH-FTMMTJW.TTF");
}
```
. But the font size is small. Please help me!
